analyzer:
  _target_: obsei.analyzer.classification_analyzer.ZeroShotClassificationAnalyzer
  device: auto
  model_name_or_path: typeform/mobilebert-uncased-mnli
analyzer_config:
  _target_: obsei.analyzer.classification_analyzer.ClassificationAnalyzerConfig
  labels:
  - blog
  - enquiry
  - wordpress
  - suggestion
  - costly
  - hosting
  - medium
  - performance
  multi_class_classification: true
sink:
  _target_: obsei.sink.SlackSink
sink_config:
  _target_: obsei.sink.SlackSinkConfig
source:
  _target_: obsei.source.TwitterSource
source_config:
  _target_: obsei.source.TwitterSourceConfig
  cred_info:
    _target_: obsei.source.TwitterCredentials
  lookup_period: 1h
  max_tweets: '30'
  query: blog suggest
