analyzer:
  _target_: obsei.analyzer.classification_analyzer.ZeroShotClassificationAnalyzer
  device: auto
  model_name_or_path: typeform/mobilebert-uncased-mnli
analyzer_config:
  _target_: obsei.analyzer.classification_analyzer.ClassificationAnalyzerConfig
  labels:
  #- blog
  #- enquiry
  #- wordpress
  #- hosting
  #- medium
  multi_class_classification: true
  use_sentiment_model: false
sink:
  _target_: obsei.sink.SlackSink
sink_config:
  _target_: obsei.sink.SlackSinkConfig
  jinja_template: |
    ```
           {%- for key, value in payload.items() recursive%}
               {%- if value is mapping -%}
      {{loop(value.items())}}
               {%- else %}
      {{key}}: {{value}}
               {%- endif %}
           {%- endfor%}
    ```
source:
  _target_: obsei.source.TwitterSource
source_config:
  _target_: obsei.source.TwitterSourceConfig
  cred_info:
    _target_: obsei.source.TwitterCredentials
  lookup_period: 3h
  max_tweets: '10'
  query: hello test
  tweet_fields:
    - "created_at"
    #- "public_metrics"
    - "text"
  user_fields:
    #- "name"
    #- "public_metrics"
    #- "username"
    #- "verified"
  expansions:  
    #- "author_id"
